import { AuditLogEntry, Car, Container, ExchangeOffice, Invoice, MoneyTransfer, Port, ShippingRoute, USState, User } from '../../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    fullName: 'مصطفى السعدي (Super Admin)',
    username: 'super.admin',
    role: 'super_admin',
    email: 'admin@carship.pro',
    phone: '+964 770 123 4567',
    isActive: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'user-2',
    fullName: 'علي الكرخي (أدمن تشغيلي)',
    username: 'ali.admin',
    role: 'admin',
    email: 'ali@carship.pro',
    phone: '+964 780 234 5678',
    isActive: true,
    createdAt: '2026-01-15',
    permissions: {
      allowedPages: ['dashboard', 'customers', 'cars', 'containers', 'invoices', 'exchange', 'calculator'],
      canAddCars: true,
      canEditCars: true,
      canDeleteCars: true,
      canCreateInvoices: true,
      canEditInvoices: true,
      canDeleteInvoices: false,
      canLockUnlockInvoices: false,
      canManageContainers: true,
      canManageExchange: true,
      canManageCustomers: true,
      canManageLogistics: false,
      canManageStaff: false,
    },
  },
  {
    id: 'user-3',
    fullName: 'حسين البصري (موظف متابعة)',
    username: 'hussein.staff',
    role: 'staff',
    email: 'hussein@carship.pro',
    phone: '+964 750 345 6789',
    isActive: true,
    createdAt: '2026-02-01',
    permissions: {
      allowedPages: ['dashboard', 'cars', 'containers', 'customers', 'calculator'],
      canAddCars: true,
      canEditCars: true,
      canDeleteCars: false,
      canCreateInvoices: false,
      canEditInvoices: false,
      canDeleteInvoices: false,
      canLockUnlockInvoices: false,
      canManageContainers: true,
      canManageExchange: false,
      canManageCustomers: true,
      canManageLogistics: false,
      canManageStaff: false,
    },
  },
  {
    id: 'user-4',
    fullName: 'أحمد مدير صيرفة الأمانة',
    username: 'amana.exchange',
    role: 'exchange_agent',
    exchangeOfficeId: 'ex-1',
    phone: '+964 771 999 8888',
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'bf58e18b-c3b8-44f0-988f-80da5057ddd7',
    fullName: 'عمر الزبيدي (زبون)',
    username: 'omar.customer',
    role: 'customer',
    email: 'omar@gmail.com',
    phone: '+964 772 111 2222',
    isActive: true,
    createdAt: '2026-02-15',
  },
];

export const MOCK_PORTS: Port[] = [
  { id: 'port-1', name: 'Savannah Port (GA)', code: 'SAV', country: 'USA', type: 'loading' },
  { id: 'port-2', name: 'New Jersey / NY Port (NJ)', code: 'NYC', country: 'USA', type: 'loading' },
  { id: 'port-3', name: 'Houston Port (TX)', code: 'HOU', country: 'USA', type: 'loading' },
  { id: 'port-4', name: 'Los Angeles Port (CA)', code: 'LAX', country: 'USA', type: 'loading' },
  { id: 'port-5', name: 'Miami Port (FL)', code: 'MIA', country: 'USA', type: 'loading' },
  // Destination Ports
  { id: 'port-10', name: 'ميناء أم قصر (العراق)', code: 'UQR', country: 'Iraq', type: 'destination', clearanceCost: 300 },
  { id: 'port-11', name: 'ميناء العقبة (الأردن)', code: 'AQB', country: 'Jordan', type: 'destination', clearanceCost: 250 },
  { id: 'port-12', name: 'ميناء جبل علي (دبي)', code: 'JEA', country: 'UAE', type: 'destination', clearanceCost: 200 },
  { id: 'port-13', name: 'ميناء بنغازي (ليبيا)', code: 'BEN', country: 'Libya', type: 'destination', clearanceCost: 200 },
  { id: 'port-14', name: 'ميناء مرسين (تركيا)', code: 'MERS', country: 'Turkey', type: 'destination', clearanceCost: 250 },
];

export const MOCK_STATES: USState[] = [
  { id: 'st-ga', code: 'GA', name: 'Georgia', defaultLoadingPortId: 'port-1', inlandCost: 350 },
  { id: 'st-tx', code: 'TX', name: 'Texas', defaultLoadingPortId: 'port-3', inlandCost: 450 },
  { id: 'st-ca', code: 'CA', name: 'California', defaultLoadingPortId: 'port-4', inlandCost: 550 },
  { id: 'st-fl', code: 'FL', name: 'Florida', defaultLoadingPortId: 'port-5', inlandCost: 400 },
  { id: 'st-nj', code: 'NJ', name: 'New Jersey', defaultLoadingPortId: 'port-2', inlandCost: 300 },
  { id: 'st-ny', code: 'NY', name: 'New York', defaultLoadingPortId: 'port-2', inlandCost: 380 },
  { id: 'st-il', code: 'IL', name: 'Illinois', defaultLoadingPortId: 'port-2', inlandCost: 650 },
  { id: 'st-mi', code: 'MI', name: 'Michigan', defaultLoadingPortId: 'port-2', inlandCost: 600 },
];

export const MOCK_ROUTES: ShippingRoute[] = [
  { id: 'r-1', loadingPortId: 'port-1', destinationPortId: 'port-10', oceanFreightCost: 1500, estimatedDays: 25 },
  { id: 'r-2', loadingPortId: 'port-3', destinationPortId: 'port-10', oceanFreightCost: 1550, estimatedDays: 28 },
  { id: 'r-3', loadingPortId: 'port-4', destinationPortId: 'port-11', oceanFreightCost: 1400, estimatedDays: 30 },
  { id: 'r-4', loadingPortId: 'port-5', destinationPortId: 'port-12', oceanFreightCost: 1300, estimatedDays: 22 },
];

export const MOCK_CARS: Car[] = [
  {
    id: 'car-1',
    customerId: 'user-5',
    customerName: 'عمر الزبيدي',
    customerPhone: '+964 772 111 2222',
    lotNumber: '54892102',
    vin: '4T1B11HK5PU123456',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2023,
    auctionName: 'Copart',
    auctionUrl: 'https://www.copart.com/lot/54892102',
    purchaseDate: '2026-08-15',
    purchasePrice: 14200,
    city: 'أتلانتا (Atlanta)',
    usStateId: 'st-ga',
    usStateName: 'Georgia (GA)',
    loadingPortName: 'Savannah Port (GA)',
    destinationPortName: 'ميناء أم قصر (العراق)',
    containerId: 'cont-1',
    containerNumber: 'MSCU-8921340',
    status: 'shipped',
    notes: 'المفتاح متوفر، صدمة خفيفة بالباب الخلفي الأيمن',
  },
  {
    id: 'car-2',
    customerId: 'user-5',
    customerName: 'عمر الزبيدي',
    customerPhone: '+964 772 111 2222',
    lotNumber: '88120411',
    vin: '1GNSKCKC4RR998877',
    make: 'Chevrolet',
    model: 'Tahoe Premier',
    year: 2024,
    auctionName: 'IAAI',
    auctionUrl: 'https://www.iaai.com/VehicleDetail/88120411',
    purchaseDate: '2026-08-18',
    purchasePrice: 31500,
    city: 'دالاس (Dallas)',
    usStateId: 'st-tx',
    usStateName: 'Texas (TX)',
    loadingPortName: 'Houston Port (TX)',
    destinationPortName: 'ميناء أم قصر (العراق)',
    containerId: 'cont-1',
    containerNumber: 'MSCU-8921340',
    status: 'shipped',
    notes: 'تشغيل وقيادة (Run & Drive)',
  },
  {
    id: 'car-3',
    customerId: 'cust-2',
    customerName: 'شركة النور لتجارة السيارات',
    customerPhone: '+964 781 444 5555',
    lotNumber: '31094822',
    vin: '1HGCV1F32NA112233',
    make: 'Honda',
    model: 'Accord Sport',
    year: 2022,
    auctionName: 'Copart',
    auctionUrl: 'https://www.copart.com/lot/31094822',
    purchaseDate: '2026-08-22',
    purchasePrice: 11800,
    city: 'أورلاندو (Orlando)',
    usStateId: 'st-fl',
    usStateName: 'Florida (FL)',
    loadingPortName: 'Miami Port (FL)',
    destinationPortName: 'ميناء جبل علي (دبي)',
    status: 'at_port',
    notes: 'بانتظار التحميل في الحاوية القادمة',
  },
  {
    id: 'car-4',
    customerId: 'cust-3',
    customerName: 'حيدر عبد الأمير',
    customerPhone: '+964 750 888 7777',
    lotNumber: '76123490',
    vin: '5UXTY5C08N9944112',
    make: 'BMW',
    model: 'X5 xDrive40i',
    year: 2023,
    auctionName: 'Copart',
    auctionUrl: 'https://www.copart.com/lot/76123490',
    purchaseDate: '2026-08-25',
    purchasePrice: 28400,
    city: 'لوس أنجلوس (Los Angeles)',
    usStateId: 'st-ca',
    usStateName: 'California (CA)',
    loadingPortName: 'Los Angeles Port (CA)',
    destinationPortName: 'ميناء العقبة (الأردن)',
    status: 'towing',
    notes: 'قيد السحب من ساحة المزاد في لوس أنجلوس للميناء',
  },
  {
    id: 'car-5',
    customerId: 'cust-4',
    customerName: 'كرار المنصوري',
    customerPhone: '+964 770 333 4444',
    lotNumber: '92837411',
    vin: '2T3P1RFV5PC556677',
    make: 'Toyota',
    model: 'RAV4 Limited',
    year: 2023,
    auctionName: 'IAAI',
    auctionUrl: 'https://www.iaai.com/VehicleDetail/92837411',
    purchaseDate: '2026-08-01',
    purchasePrice: 16900,
    city: 'نيوارك (Newark)',
    usStateId: 'st-nj',
    usStateName: 'New Jersey (NJ)',
    loadingPortName: 'New Jersey / NY Port (NJ)',
    destinationPortName: 'ميناء أم قصر (العراق)',
    containerId: 'cont-2',
    containerNumber: 'CMAU-4501982',
    status: 'arrived',
    notes: 'وصلت الميناء وبانتظار دفع الرسوم الجمركية والتسليم',
  },
];

export const MOCK_CONTAINERS: Container[] = [
  {
    id: 'cont-1',
    containerNumber: 'MSCU-8921340',
    bookingNumber: 'BK-2026-9921',
    trackingUrl: 'https://www.msc.com/track-a-shipment?reference=MSCU-8921340',
    shippingLine: 'MSC Mediterranean Shipping Company',
    loadingPort: 'Savannah Port (GA)',
    destinationPort: 'ميناء أم قصر (العراق)',
    departureDate: '2026-08-20',
    estimatedArrival: '2026-09-25',
    capacity: 4,
    status: 'on_sea',
    carIds: ['car-1', 'car-2'],
  },
  {
    id: 'cont-2',
    containerNumber: 'CMAU-4501982',
    bookingNumber: 'BK-2026-7811',
    trackingUrl: 'https://www.cma-cgm.com/ebusiness/tracking/CMAU-4501982',
    shippingLine: 'CMA CGM',
    loadingPort: 'New Jersey (NJ)',
    destinationPort: 'ميناء أم قصر (العراق)',
    departureDate: '2026-07-28',
    estimatedArrival: '2026-08-28',
    capacity: 4,
    status: 'arrived',
    carIds: ['car-5'],
  },
];

export const MOCK_EXCHANGE_OFFICES: ExchangeOffice[] = [
  {
    id: 'ex-1',
    name: 'شركة الأمانة للصيرفة والتحويل المالي',
    city: 'بغداد - الكرادة',
    contactPerson: 'الحاج أحمد الربيعي',
    phone: '+964 771 999 8888',
    balanceUsd: 15400, // بذمة الصيرفة لصالحنا
  },
  {
    id: 'ex-2',
    name: 'شركة الطيف للصرافة',
    city: 'أربيل - شارع 60',
    contactPerson: 'ريبوار حسن',
    phone: '+964 750 111 9900',
    balanceUsd: -4200, // مستحق للصيرفة بذمتنا
  },
  {
    id: 'ex-3',
    name: 'مكتب دبي للوساطة المالية',
    city: 'دبي - ديرة',
    contactPerson: 'محمد المري',
    phone: '+971 50 123 4567',
    balanceUsd: 8900, // بذمتهم لصالحنا
  },
];

export const MOCK_TRANSFERS: MoneyTransfer[] = [
  {
    id: 'tr-1',
    transferNumber: 'TRF-2026-0881',
    exchangeOfficeId: 'ex-1',
    exchangeOfficeName: 'شركة الأمانة للصيرفة',
    carId: 'car-1',
    carLot: '54892102',
    purpose: 'car_purchase',
    direction: 'inbound',
    originalAmount: 14200,
    currency: 'USD',
    exchangeRate: 1.0,
    amountUsd: 14200,
    location: 'بغداد',
    receivedAt: '2026-08-16',
    notes: 'دفعة شراء تويوتا كامري',
    isAiAction: false,
  },
  {
    id: 'tr-2',
    transferNumber: 'TRF-2026-0895',
    exchangeOfficeId: 'ex-1',
    exchangeOfficeName: 'شركة الأمانة للصيرفة',
    carId: 'car-1',
    carLot: '54892102',
    purpose: 'shipping_cost',
    direction: 'inbound',
    originalAmount: 2830500,
    currency: 'IQD',
    exchangeRate: 1530,
    amountUsd: 1850,
    location: 'بغداد',
    receivedAt: '2026-08-18',
    notes: 'أجور الشحن البحري والداخلي',
    isAiAction: true,
  },
  {
    id: 'tr-3',
    transferNumber: 'TRF-2026-0902',
    exchangeOfficeId: 'ex-3',
    exchangeOfficeName: 'مكتب دبي للوساطة',
    carId: 'car-2',
    carLot: '88120411',
    purpose: 'combined',
    direction: 'inbound',
    originalAmount: 33400,
    currency: 'USD',
    exchangeRate: 1.0,
    amountUsd: 33400,
    location: 'دبي',
    receivedAt: '2026-08-19',
    notes: 'دفعة تاهو 2024 كاملة (شراء + شحن)',
    isAiAction: false,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2026-0042',
    carId: 'car-1',
    shippingCost: 1850,
    commissionPercent: 1.5,
    commissionAmount: 213,
    subtotal: 16263,
    discount: 100,
    discountReason: 'خصم ولاء العميل والتعامل المستمر',
    netTotal: 16163,
    paidAmount: 16163,
    remainingAmount: 0,
    isLocked: true,
    lockedAt: '2026-08-20',
    customFields: [
      { id: 'f-1', fieldName: 'أجور تأخير أرضيات المزاد (Late Fee)', fieldAmount: 50 },
    ],
    createdAt: '2026-08-16',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2026-0043',
    carId: 'car-2',
    shippingCost: 1900,
    commissionPercent: 1.0,
    commissionAmount: 315,
    subtotal: 33715,
    discount: 0,
    netTotal: 33715,
    paidAmount: 33400,
    remainingAmount: 315,
    isLocked: false,
    customFields: [],
    createdAt: '2026-08-19',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-2026-0044',
    carId: 'car-3',
    shippingCost: 1650,
    commissionPercent: 2.0,
    commissionAmount: 236,
    subtotal: 13686,
    discount: 150,
    discountReason: 'خصم شحن حاوية كاملة',
    netTotal: 13536,
    paidAmount: 10000,
    remainingAmount: 3536,
    isLocked: false,
    customFields: [
      { id: 'f-2', fieldName: 'أجور عمل مفتاح إضافي (Key Service)', fieldAmount: 120 },
    ],
    createdAt: '2026-08-23',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    userId: 'user-3',
    userName: 'حسين البصري (موظف متابعة)',
    userRole: 'staff',
    action: 'UPDATE_CAR_STATUS',
    actionTitle: 'تحديث حالة الشحن للسيارة Toyota Camry 2024',
    entityType: 'car',
    entityId: 'car-1',
    details: 'تم تغيير حالة الشحن من "في ساحة المزاد" إلى "نقل داخلي بأمريكا (Towing)" وتعيين السائق.',
    timestamp: '2026-09-10T10:15:00Z',
  },
  {
    id: 'log-2',
    userId: 'user-3',
    userName: 'حسين البصري (موظف متابعة)',
    userRole: 'staff',
    action: 'ASSIGN_CONTAINER',
    actionTitle: 'ربط سيارة بالحاوية البحرية MEDU7849102',
    entityType: 'container',
    entityId: 'cont-1',
    details: 'تم إدراج السيارة Ford Mustang 2023 ضمن حمولة الحاوية المتجهة لميناء أم قصر.',
    timestamp: '2026-09-10T11:30:00Z',
  },
  {
    id: 'log-3',
    userId: 'user-2',
    userName: 'علي الكرخي (أدمن تشغيلي)',
    userRole: 'admin',
    action: 'CREATE_CAR',
    actionTitle: 'إضافة سيارة جديدة: 2024 Chevrolet Tahoe',
    entityType: 'car',
    entityId: 'car-2',
    details: 'تم تسجيل السيارة برقم لوت 84920152 وسعر شراء $31,500 من مزاد Copart للعميل عمر الزبيدي.',
    timestamp: '2026-09-09T14:20:00Z',
  },
  {
    id: 'log-4',
    userId: 'user-1',
    userName: 'مصطفى السعدي (Super Admin)',
    userRole: 'super_admin',
    action: 'LOCK_INVOICE',
    actionTitle: 'قفل الفاتورة رقم INV-2026-0042 نهائياً',
    entityType: 'invoice',
    entityId: 'inv-1',
    details: 'تم اعتماد وقفل الفاتورة المالية بعد استلام سند القبض وإرفاق تفاصيل الشحن.',
    timestamp: '2026-09-08T09:45:00Z',
  },
  {
    id: 'log-5',
    userId: 'user-3',
    userName: 'حسين البصري (موظف متابعة)',
    userRole: 'staff',
    action: 'SEND_CAR_MESSAGE',
    actionTitle: 'إرسال تحديث للعميل حول وصول السيارة للميناء',
    entityType: 'car',
    entityId: 'car-1',
    details: 'تم إرسال رسالة نصية للعميل: وصلت السيارة إلى ميناء سافانا بانتظار التحميل البحري.',
    timestamp: '2026-09-07T16:00:00Z',
  },
  {
    id: 'log-6',
    userId: 'user-2',
    userName: 'علي الكرخي (أدمن تشغيلي)',
    userRole: 'admin',
    action: 'CREATE_TRANSFER',
    actionTitle: 'تسجيل قيد حوالة مالية بقيمة $15,000',
    entityType: 'transfer',
    entityId: 'tr-1',
    details: 'تم تسجيل حوالة مقبوضة من صيرفة الأمانة لصالح كشف حساب العميل.',
    timestamp: '2026-09-06T12:10:00Z',
  },
];
